import Head from 'next/head';
import Sidebar from '../components/sidebar/sidebar';
import Header from '../components/header/header';
import Realtors from '../components/realtors/realtors';
import Features from '../components/features/features';
import StoryPictures from '../components/story/story-pictures';
import StoryContent from '../components/story/story-content';
import Homes from '../components/homes/homes';
import Gallery from '../components/gallery/gallery';
import Footer from '../components/footer/footer';
import Container from '../components/ui/container';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Nexters</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,400i|Nunito:300,300i"
                    rel="stylesheet"
                />
            </Head>

            <Container>

                <Sidebar />

                <Header />

                <Realtors />

                <Features />

                <StoryPictures />

                <StoryContent />

                <Homes />

                <Gallery />

                <Footer />
                
            </Container>
        </div>
    );
}
